name: Publish Extension

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.18.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'npm'

      - name: Verify Node
        run: node -v && npm -v

      - name: Install dependencies
        run: npm ci

      - name: Install vsce and ovsx
        run: npm install -g @vscode/vsce ovsx

      - name: Publish to VSCode Marketplace
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX
        run: ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
